# Deletes head branches after a PR is merged EXCEPT for main and sprint/** branches

# While GH natively supports automatically deleting head branches on click of Merge button, they
# allow no branch filter (except !default-branch). We do NOT want sprint/** branches deleted on
# PR merge since that will delete their corresponding deployment per the DELETE_BRANCH_CI workflow.

name: PR Merge - delete head branch if not main or sprint

on:
  pull_request:
    types: [closed]

jobs:
  delete-merged-branch-if-not-main-or-sprint:
    if: |
      github.event.pull_request.merged == true && 
      github.event.pull_request.head.ref != 'main' && 
      !startsWith(github.event.pull_request.head.ref, 'sprint')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          git fetch
          git push origin --delete ${{ github.event.pull_request.head.ref }}
          git fetch --all && git remote prune origin
